modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="tooltipareapatch"
version="${file.jarVersion}"
displayName="Tooltip Area Patch"
description="""Client-side tooltip positioning utility."""
[[dependencies.tooltipareapatch]]
modId="forge"
mandatory=true
versionRange="[47,)"
side="CLIENT"
[[dependencies.tooltipareapatch]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
side="CLIENT"
